version: "3.7"

services:

    postgres:
        container_name: vpp-db
        hostname: postgres
        image: postgres
        volumes:
            - ./tmp/pgData:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: dev_vpp
            POSTGRES_USER: dev_dbuser_vpp
            POSTGRES_PASSWORD: password

    redis:
        container_name: vpp-redis
        hostname: vpp-redis
        image: redis:5.0.7
        volumes:
            - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
        ports:
            - "6379:6379"

    mailcatcher:
        # restart: on-failure:10
        hostname: vpp-mailcatcher
        container_name: vpp-mailcatcher
        image: dockage/mailcatcher:0.7.1
        ports:
            - "1080:1080"
            - "1025:1025"

    nginx:
        container_name: vpp-nginx
        hostname: vpp-nginx
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./:/var/www/
            - ../vpp-retail:/var/www2
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    php:
        container_name: vpp-php
        hostname: vpp-php
        build:
            context: ./docker/php
        ports:
            - 9000:9000

        volumes:
            - ./:/var/www/
            - ../vpp-retail:/var/www2
            - ../vpp-officemanager:/var/www3
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
            # - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
